# Generated by Django 5.2.5 on 2025-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveloption',
            name='type',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('cab', 'Cab')], max_length=10),
        ),
    ]
